# Generated by Django 3.0.6 on 2020-06-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap', models.CharField(db_index=True, max_length=150, verbose_name='металл')),
                ('cost', models.FloatField(verbose_name='цена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'металл',
                'verbose_name_plural': 'металлы',
            },
        ),
    ]
