# Generated by Django 2.1.4 on 2018-12-29 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap', models.CharField(db_index=True, max_length=150)),
                ('cost', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_refresh', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
