# Generated by Django 2.1.4 on 2018-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181229_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='date_refresh',
            new_name='created',
        ),
        migrations.AddField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
