# Generated by Django 2.1.4 on 2019-01-06 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181229_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
