# Generated by Django 2.1.4 on 2019-01-06 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190106_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
