# Generated by Django 2.1.4 on 2019-01-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190106_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.FloatField(),
        ),
    ]
