# Generated by Django 2.1 on 2019-06-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_feedback_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='scrap',
            new_name='metal',
        ),
    ]
