# Generated by Django 2.1 on 2019-06-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190609_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='metal',
            new_name='scrap',
        ),
    ]
